# Default Theme

if patched_font_in_use; then
	#TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="⮂"
	#TMUX_POWERLINE_SEPARATOR_LEFT_THIN="⮃"
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="⮂"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="⮃"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="⮀"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="⮁"
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'235'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}


# Format: segment_name background_color foreground_color [non_default_separator]

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		#"tmux_session_info 148 234" \
		#"ifstat 30 255" \
		"lan_ip 79 0 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}" \
		#"wan_ip 24 255" \
		#"vcs_branch 29 88" \
		#"vcs_compare 60 255" \
		#"vcs_staged 64 255" \
		#"vcs_modified 9 255" \
		#"vcs_others 245 0" \
	)
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		#"earthquake 3 0" \
		#"mailcount 9 255" \
		#"now_playing 234 37" \
		#"hostname 118 0" \
		#"cpu 119 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"mem 120 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
                #"lan_ip 121 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"hostname 121 0" \
		"stock 122 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"weather 123 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"date 87 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"date_day 86 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"time 85 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \

		#"cpu 120 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"mem 121 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"load 122 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"battery 137 127" \
		#"rainbarf 0 0" \
		#"xkb_layout 125 117" \
		#"weather 122 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"stock 123 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"date 87 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"date_day 86 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"time 85 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"utc_time 235 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
	)
fi
